server:
  port: 8888

spring:
  application:
    name: rag-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ssehgal91/rag-microservices-platform.git
          clone-on-start: true
          search-paths: rag-config-repo
          default-label: main